apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: clusterx-h9gtz
  name: clusterx-h9gtz-infra
  namespace: openshift-machine-api
spec:
  replicas: 5
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: clusterx-h9gtz
      machine.openshift.io/cluster-api-machineset: clusterx-h9gtz-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: clusterx-h9gtz
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: clusterx-h9gtz-infra
    spec:
      metadata:
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 32768
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: dvPG_VLAN361-OCLAB
          numCPUs: 8
          numCoresPerSocket: 8
          snapshot: ""
          template: clusterx-h9gtz-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: Markham 6.7
            datastore: purefa-mrk1-clusterx-ds01
            folder: /Markham 6.7/vm/clusterx-h9gtz
            resourcePool: /Markham 6.7/host/MRK_CLUSTERX/Resources
            server: si2vpavc04.canada01.ifdsnet.int
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
