apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: clusterq1
  namespace: clusterq1
  labels:
    app.kubernetes.io/instance: clusterq1
spec:
  clusterName: clusterq1
  clusterNamespace: clusterq1
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
#    argocdCluster: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
