apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: clusterx1
  namespace: clusterx1
spec:
  clusterName: clusterx1
  clusterNamespace: clusterx1
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
    argocdCluster: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
